dist: xenial
language: python
python:
  - '3.7.1'
install:
  - pip install -r requirements.txt
script:
  - docker stop mongodb
  - docker run -d -p 27017-27019:27017-27019 --name mongodb --rm mongo
  - python run_engine.py
  - python -m unittest